services:
  db:
    image: mariadb:12.3
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: taskManagerDb
      MARIADB_USER: taskuser
      MARIADB_PASSWORD: taskpass
    ports:
      - "3306:3306"
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DefaultConnection=Server=db;Database=taskManagerDb;Uid=taskuser;Pwd=taskpass
    ports:
      - "8080:8080"
  
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
